export const ai_courses = [
	{
		id: 'ai-for-everyone',
		name: 'AI For Everyone',
		tagline: 'Non-technical AI literacy for business & decision makers',
		desc: "Andrew Ng's acclaimed course demystifying AI for non-engineers. Covers what AI can and can't do, how to spot opportunities, and how to work alongside technical teams. Essential for managers and founders.",
		pros: [
			'Taught by Andrew Ng (world-renowned)',
			'No coding required',
			'Free to audit on Coursera',
		],
		cons: ['Too basic for engineers', "Won't teach you to build anything"],
		href: 'https://www.coursera.org/learn/ai-for-everyone',
	},
	{
		id: 'fast-ai',
		name: 'Practical Deep Learning (fast.ai)',
		tagline: 'Top-down, hands-on deep learning for coders',
		desc: "Jeremy Howard's legendary free course that gets you building real models fast. Starts with applications, works backwards to theory — the opposite of most courses. Highly respected in the ML community.",
		pros: ['Completely free', 'Practical-first approach', 'Strong community'],
		cons: ['Requires Python knowledge', 'Self-paced with no hand-holding'],
		href: 'https://course.fast.ai',
	},
	{
		id: 'deeplearning-specialization',
		name: 'Deep Learning Specialization',
		tagline: '5-course deep dive into neural networks & modern AI',
		desc: 'The gold-standard structured curriculum from Andrew Ng on Coursera. Covers neural networks, CNNs, RNNs, and tuning in depth. Best rigorous path for developers entering ML seriously.',
		pros: [
			'Industry-recognised certificate',
			'Very structured',
			'Strong maths foundation',
		],
		cons: ['Takes months to complete', 'Paid for graded assignments'],
		href: 'https://www.coursera.org/specializations/deep-learning',
	},
	{
		id: 'prompt-engineering-deeplearning',
		name: 'ChatGPT Prompt Engineering for Developers',
		tagline: 'Learn to prompt LLMs effectively — by OpenAI & DeepLearning.AI',
		desc: 'Short, free course co-created by OpenAI and Andrew Ng. Teaches best practices for prompting GPT models in real applications — summarisation, extraction, transformation. Ideal for developers integrating LLMs.',
		pros: ['Free', 'Short (2–3 hrs)', 'Straight from OpenAI'],
		cons: ['Beginner level only', 'Focused on ChatGPT specifically'],
		href: 'https://www.deeplearning.ai/short-courses/chatgpt-prompt-engineering-for-developers/',
	},
	{
		id: 'huggingface-nlp',
		name: 'HuggingFace NLP Course',
		tagline: 'Open-source NLP & Transformers from the source',
		desc: 'Official free course from HuggingFace covering Transformers, tokenisers, fine-tuning, and deploying models. The best way to go from zero to working with BERT, GPT and similar models.',
		pros: [
			'Free & constantly updated',
			'Directly tied to the HF ecosystem',
			'Practical with real code',
		],
		cons: ['Requires Python & ML basics', 'Dense in places'],
		href: 'https://huggingface.co/learn/nlp-course/chapter1/1',
	},
	{
		id: 'google-ml-crash-course',
		name: 'Google ML Crash Course',
		tagline: "Google's own intro to machine learning with TensorFlow",
		desc: 'Free, self-paced course from Google covering ML fundamentals, feature engineering, and neural networks using TensorFlow. Built for software engineers new to ML.',
		pros: [
			'Free from Google',
			'Good pacing for engineers',
			'Includes exercises',
		],
		cons: ['TensorFlow-focused', 'Less deep than full specialisations'],
		href: 'https://developers.google.com/machine-learning/crash-course',
	},
	{
		id: 'langchain-llm-apps',
		name: 'LangChain for LLM Application Development',
		tagline: 'Build LLM-powered apps with LangChain — free short course',
		desc: 'Short DeepLearning.AI course teaching how to chain LLM calls, use memory, build agents and work with document Q&A. Directly practical for anyone building AI-powered products.',
		pros: ['Free', 'Very practical', 'Covers modern agent patterns'],
		cons: ['Fast-moving ecosystem (may go stale)', 'Requires Python basics'],
		href: 'https://www.deeplearning.ai/short-courses/langchain-for-llm-application-development/',
	},
	{
		id: 'cs229-stanford',
		name: 'Stanford CS229: Machine Learning',
		tagline: 'Rigorous academic ML — the original Andrew Ng Stanford course',
		desc: 'The legendary Stanford course that started it all. Full lecture notes and videos freely available. Covers supervised, unsupervised, and reinforcement learning with strong mathematical grounding.',
		pros: [
			'World-class depth',
			'Free lecture notes & videos',
			'Great for strong foundations',
		],
		cons: ['Very maths-heavy', 'No certificate for free version'],
		href: 'https://cs229.stanford.edu',
	},
	{
		id: 'udemy-ml-az',
		name: 'Machine Learning A–Z (Udemy)',
		tagline: 'Broad practical ML survey — Python & R',
		desc: 'One of the most popular ML courses on Udemy covering regression, classification, clustering, NLP and more in both Python and R. Good for career-changers who want a broad map of the field.',
		pros: [
			'Affordable (frequent sales)',
			'Very broad coverage',
			'Lifetime access',
		],
		cons: ['Can feel shallow on individual topics', 'Older content in places'],
		href: 'https://www.udemy.com/course/machinelearning/',
	},
	{
		id: 'rag-deeplearning',
		name: 'Building and Evaluating Advanced RAG',
		tagline: 'Learn Retrieval-Augmented Generation end to end',
		desc: 'Focused DeepLearning.AI short course on building RAG pipelines — chunking, embedding, retrieval, re-ranking and evaluation. Critical knowledge for anyone building AI search or knowledge tools.',
		pros: [
			'Free',
			'Highly relevant in 2024+',
			'Covers evaluation (often overlooked)',
		],
		cons: ['Assumes LLM basics', 'Short — leaves some topics at surface level'],
		href: 'https://www.deeplearning.ai/short-courses/building-evaluating-advanced-rag/',
	},
];
