export const ai_tools = [
	{
		id: 'chatgpt',
		name: 'ChatGPT',
		tagline: 'All-round AI assistant: writing, research, coding, conversation',
		desc: 'The most widely used AI tool in the world. Handles everything from drafting content and writing code to research, analysis and conversation. GPT-4o is genuinely powerful for almost any task.',
		pros: [
			'Huge ecosystem & plugins',
			'Multimodal — text, image, voice',
			'Most capable generalist model',
		],
		cons: [
			'Cost ramps up for heavy API use',
			'Generic output without good prompting',
		],
		affiliate: 'https://chat.openai.com',
	},
	{
		id: 'claude',
		name: 'Claude',
		tagline: 'Safe, style-aware AI for long-form & structured content',
		desc: "Anthropic's AI excels at long documents, nuanced writing, and following complex instructions. Favoured for reliability, tone control, and lower hallucination rates than most competitors.",
		pros: [
			'Outstanding for long-form content',
			'Excellent instruction following',
			'Lower hallucination rate',
		],
		cons: [
			'Smaller plugin ecosystem than ChatGPT',
			'Slower on very complex tasks',
		],
		affiliate: 'https://claude.ai',
	},
	{
		id: 'perplexity',
		name: 'Perplexity AI',
		tagline: 'Search-first AI with live data & source citations',
		desc: 'The best AI for research. Perplexity searches the web in real time and always cites its sources — ideal when you need accurate, up-to-date information rather than generated text.',
		pros: [
			'Live web search built in',
			'Every answer is cited',
			'Great for fact-checking & research',
		],
		cons: ['Less strong for creative writing', 'Free tier has daily limits'],
		affiliate: 'https://www.perplexity.ai',
	},
	{
		id: 'gemini',
		name: 'Gemini',
		tagline: "Google's multimodal AI — deeply integrated with Workspace",
		desc: "Google's flagship AI model, deeply integrated with Gmail, Docs, Sheets and Drive. Gemini 1.5 Pro handles enormous context windows and is excellent for analysing large documents.",
		pros: [
			'Native Google Workspace integration',
			'Huge 1M token context window',
			'Strong multimodal capabilities',
		],
		cons: [
			'Uneven quality on creative tasks',
			'Privacy concerns for business use',
		],
		affiliate: 'https://gemini.google.com',
	},
	{
		id: 'cursor',
		name: 'Cursor',
		tagline: 'AI-first code editor — the best tool for developers',
		desc: 'A VS Code fork with AI deeply integrated throughout. Cursor can understand your entire codebase, write and edit code inline, and fix bugs with a single prompt. The go-to tool for AI-assisted development.',
		pros: [
			'Understands your whole codebase',
			'Inline edits & autocomplete',
			'Works with any language or framework',
		],
		cons: ['Subscription required for full power', 'Takes time to set up well'],
		affiliate: 'https://www.cursor.com',
	},
	{
		id: 'midjourney',
		name: 'Midjourney',
		tagline: 'The best AI image generation tool available',
		desc: 'Consistently produces the highest quality AI images of any tool. Used by designers, marketers and creators worldwide for everything from social assets to concept art. Runs via Discord.',
		pros: [
			'Best image quality available',
			'Active community & styles',
			'Rapid iteration with variations',
		],
		cons: ['Discord-only interface', 'No free tier'],
		affiliate: 'https://www.midjourney.com',
	},
	{
		id: 'notion-ai',
		name: 'Notion AI',
		tagline: 'AI writing & summarisation built into your workspace',
		desc: 'If you already use Notion, the AI add-on is a no-brainer. Summarise pages, draft content, extract action items from notes, and autofill databases — all without leaving your workflow.',
		pros: [
			'Seamlessly embedded in Notion',
			'Great for summarising meeting notes',
			'Autofill databases with AI',
		],
		cons: ['Only useful if you use Notion', 'Extra cost on top of Notion plan'],
		affiliate: 'https://www.notion.so/product/ai',
	},
	{
		id: 'jasper',
		name: 'Jasper',
		tagline: 'Enterprise AI copywriting for marketing teams',
		desc: 'Template-driven AI copywriter built for marketing teams and agencies. Handles long-form content, ad copy, social posts and brand voice — with collaboration features for larger teams.',
		pros: [
			'30% recurring affiliate commission',
			'Brand voice & style memory',
			'Built for marketing workflows',
		],
		cons: ['Expensive for solo creators', 'Overkill for simple writing tasks'],
		affiliate: 'https://www.jasper.ai',
	},
	{
		id: 'elevenlabs',
		name: 'ElevenLabs',
		tagline: 'Hyper-realistic AI voice generation & cloning',
		desc: 'The leading AI voice platform. Generate natural-sounding voiceovers in any language, clone voices, and create audio content at scale. Used by podcasters, video creators and developers.',
		pros: [
			'Most realistic AI voices available',
			'Voice cloning from short samples',
			'Supports 30+ languages',
		],
		cons: [
			'Free tier has limited characters',
			'Voice cloning raises ethical considerations',
		],
		affiliate: 'https://elevenlabs.io',
	},
	{
		id: 'runway',
		name: 'Runway',
		tagline: 'AI video generation & editing for creators',
		desc: 'The most capable AI video tool for creators. Generate video from text or images, remove backgrounds, edit with AI, and produce cinematic content without a production team.',
		pros: [
			'Text-to-video generation',
			'Powerful AI video editing tools',
			'Constantly shipping new models',
		],
		cons: [
			'Credits run out fast on free plan',
			'High quality outputs need paid tiers',
		],
		affiliate: 'https://runwayml.com',
	},
	{
		id: 'frase',
		name: 'Frase',
		tagline: 'AI content research & SEO brief writing',
		desc: 'Combines live SERP analysis with AI-assisted content briefs and drafting. Built for SEO content creators who want research, structure and writing in one streamlined tool.',
		pros: [
			'SERP analysis built in',
			'Research-to-draft workflow',
			'Strong for SEO content',
		],
		cons: ['Steep learning curve', 'Less useful for non-SEO writing'],
		affiliate: 'https://www.frase.io',
	},
	{
		id: 'canva-ai',
		name: 'Canva AI',
		tagline: 'Design + AI tools for non-designers',
		desc: "Canva's AI features (Magic Design, text-to-image, Magic Write) make it the easiest way for non-designers to create polished visuals, presentations and social content at speed.",
		pros: [
			'Extremely easy to use',
			'AI + design tools in one place',
			'Generous free tier',
		],
		cons: [
			'Not a professional design suite',
			'AI image quality lags behind Midjourney',
		],
		affiliate: 'https://www.canva.com',
	},
];
