export const ai_tools = [
	{
		id: 'jasper',
		name: 'Jasper',
		tagline: 'AI copywriting assistant for marketers',
		desc: 'Template-driven AI copywriter that helps create long-form content, social posts and ad copy quickly. Great for teams and agencies.',
		pros: ['30% recurring affiliate', 'Great templates', 'Team features'],
		cons: ['Can be pricey for solo creators'],
		affiliate: '#aff-jasper',
	},
	{
		id: 'writesonic',
		name: 'Writesonic',
		tagline: 'Versatile AI writing + conversational tools',
		desc: 'A flexible suite that includes blog writers, landing page copy and ChatSonic (conversational AI). Strong for quick experiments.',
		pros: ['Easy to use', 'Affordable tiers'],
		cons: ['Occasional inconsistency in tone'],
		affiliate: '#aff-writesonic',
	},
	{
		id: 'rytr',
		name: 'Rytr',
		tagline: 'Budget-friendly AI writer for beginners',
		desc: 'Simple, budget-first tool for generating short-form content and quick drafts. Nice onboarding for first-time AI users.',
		pros: ['Low cost', 'Fast outputs'],
		cons: ['Limited advanced features'],
		affiliate: '#aff-rytr',
	},
	{
		id: 'frase',
		name: 'Frase',
		tagline: 'AI for SEO-driven content research',
		desc: 'Combines SERP analysis with content briefs and AI drafting — perfect for SEO-first creators who want research baked into writing.',
		pros: ['SEO integrations', 'Research + write flow'],
		cons: ['Learning curve for full power'],
		affiliate: '#aff-frase',
	},
	{
		id: 'canva',
		name: 'Canva AI',
		tagline: 'Design + AI tools for visuals',
		desc: 'Design-first platform that now includes powerful AI features (text-to-image, Magic Design) — great for non-designers creating assets fast.',
		pros: ['Familiar UI', 'Great for visuals'],
		cons: ['Not a full creative suite for pros'],
		affiliate: '#aff-canva',
	},
	{
		id: 'chatgpt',
		name: 'ChatGPT (OpenAI)',
		tagline: 'All-round AI assistant: writing, research, coding, conversation',
		desc: 'Very versatile tool useful for everything from drafting long-form content, ideation, code generation, to conversational tasks. Strong with multimodal inputs in newer versions. Great generalist AI. ',
		pros: [
			'Strong reasoning & context',
			'Integrations / plugins',
			'Latest models are smart & powerful',
		],
		cons: [
			'Cost can ramp up for heavy users',
			'Sometimes output is generic without good prompting',
		],
		affiliate: '#aff-chatgpt',
	},
	{
		id: 'claude',
		name: 'Claude (Anthropic)',
		tagline: 'Safe, style-aware AI for long-form & structured content',
		desc: 'Good at handling long documents, more control over tone / writing style, becoming more capable with updates. Favoured where reliability and style matter. ',
		pros: [
			'Style presets / personalization',
			'Good for longer content & structure',
			'Safety and low hallucination bias (comparatively)',
		],
		cons: [
			'May lag behind in plugin / ecosystem integrations',
			'occasional slower outputs on very complex tasks',
		],
		affiliate: '#aff-claude',
	},
	{
		id: 'perplexity',
		name: 'Perplexity AI',
		tagline: 'Search-first AI with source citations & fresh info',
		desc: 'Excellent tool when you need research, up-to-date facts and sources. Also useful for summarisation and for when verifiable accuracy is important. ',
		pros: [
			'Live / recent data',
			'Citations & sources',
			'Good for answering questions & research tasks',
		],
		cons: [
			'Less strong for creative writing tone / style polish',
			'free / lower tiers can have limits',
		],
		affiliate: '#aff-perplexity',
	},
	{
		id: 'predis',
		name: 'Predis.ai',
		tagline: 'Social media content + scheduling with AI',
		desc: 'Focused on creators / marketers who need visuals, captions, scheduling, competitor analysis, multi-brand workflows. Blends content generation with social media tools. ',
		pros: [
			'Good for social media creativity (carousel, video ads etc.)',
			'Competitor analysis & scheduling included',
			'Scales to teams / brands',
		],
		cons: [
			'Price gets steep when using many channels / output credits',
			'may be overkill if you just want text',
		],
		affiliate: '#aff-predis',
	},
	{
		id: 'wordtune',
		name: 'Wordtune',
		tagline: 'Refine writing: tone, clarity, paraphrase & polishing',
		desc: 'More focused on rewriting & improving existing text: paraphrasing, tone adjustment, clarity, grammar. Useful as polish-tool after first draft. ',
		pros: [
			'Strong at rewriting and style tuning',
			'Chrome extension / ease of use',
			'Free plan available, affordable upgrades',
		],
		cons: [
			'Limited major creative content generation',
			'heavy use can require higher plans for unlimited features',
			'less suited for visual & design',
		],
		affiliate: '#aff-wordtune',
	},
];
