export const ai_topics = [
	{
		id: 'prompt-engineering',
		name: 'Prompt Engineering',
		desc: 'Master the skill of communicating with AI models. From basic instructions to advanced chain-of-thought techniques that get dramatically better results.',
		icon: 'Zap',
		color: 'indigo',
		tag: 'prompt engineering',
		articleCount: 4,
		toolCount: 3,
		courseCount: 3,
	},
	{
		id: 'ai-writing-tools',
		name: 'AI Writing Tools',
		desc: 'The best AI tools for writing, editing and content creation — from long-form blog posts to ad copy, emails and social content.',
		icon: 'PenLine',
		color: 'violet',
		tag: 'AI writing tools',
		articleCount: 3,
		toolCount: 5,
		courseCount: 2,
	},
	{
		id: 'llms',
		name: 'Large Language Models',
		desc: 'Understand how LLMs like GPT-4, Claude and Gemini actually work — from transformers and tokens to context windows and hallucinations.',
		icon: 'Brain',
		color: 'blue',
		tag: 'LLMs',
		articleCount: 4,
		toolCount: 3,
		courseCount: 4,
	},
	{
		id: 'ai-for-business',
		name: 'AI for Business',
		desc: 'Practical ways businesses are saving time and money with AI — from automating workflows and customer support to sales, marketing and ops.',
		icon: 'Briefcase',
		color: 'emerald',
		tag: 'AI business',
		articleCount: 3,
		toolCount: 4,
		courseCount: 2,
	},
	{
		id: 'ai-image-generation',
		name: 'AI Image Generation',
		desc: 'Everything about generating images with AI — Midjourney, DALL·E, Stable Diffusion, prompting techniques and the best use cases for each.',
		icon: 'Image',
		color: 'pink',
		tag: 'AI image generation',
		articleCount: 2,
		toolCount: 2,
		courseCount: 1,
	},
	{
		id: 'ai-for-seo',
		name: 'AI for SEO',
		desc: 'Use AI to research keywords, build content briefs, write optimised articles and scale your SEO content operation without scaling your team.',
		icon: 'Search',
		color: 'amber',
		tag: 'AI for SEO',
		articleCount: 2,
		toolCount: 3,
		courseCount: 1,
	},
	{
		id: 'ai-productivity',
		name: 'AI Productivity',
		desc: 'The AI tools and techniques professionals use to save 10+ hours per week — automating email, research, meeting notes and repetitive tasks.',
		icon: 'Rocket',
		color: 'teal',
		tag: 'AI productivity',
		articleCount: 3,
		toolCount: 4,
		courseCount: 2,
	},
	{
		id: 'ai-for-developers',
		name: 'AI for Developers',
		desc: 'AI tools and techniques built for developers — from Cursor and GitHub Copilot to RAG pipelines, LangChain and building your own AI products.',
		icon: 'Code2',
		color: 'slate',
		tag: 'developers',
		articleCount: 3,
		toolCount: 3,
		courseCount: 4,
	},
	{
		id: 'rag',
		name: 'RAG & Vector Databases',
		desc: 'Retrieval-Augmented Generation explained — how to build AI systems that search and reference your own documents, databases and knowledge bases.',
		icon: 'Database',
		color: 'cyan',
		tag: 'RAG',
		articleCount: 2,
		toolCount: 1,
		courseCount: 2,
	},
	{
		id: 'ai-comparisons',
		name: 'AI Comparisons',
		desc: 'Head-to-head comparisons of the top AI tools and models — ChatGPT vs Claude, Midjourney vs DALL·E, and which AI wins for each use case.',
		icon: 'GitCompare',
		color: 'rose',
		tag: 'AI comparison',
		articleCount: 4,
		toolCount: 0,
		courseCount: 0,
	},
	{
		id: 'ai-for-creators',
		name: 'AI for Creators',
		desc: 'How content creators, YouTubers, podcasters and designers are using AI tools to produce more content faster without sacrificing quality.',
		icon: 'Sparkles',
		color: 'fuchsia',
		tag: 'content creation',
		articleCount: 2,
		toolCount: 5,
		courseCount: 2,
	},
	{
		id: 'machine-learning',
		name: 'Machine Learning',
		desc: 'Learn the fundamentals of machine learning — from supervised and unsupervised learning to neural networks, model training and evaluation.',
		icon: 'Cpu',
		color: 'green',
		tag: 'machine learning',
		articleCount: 2,
		toolCount: 1,
		courseCount: 5,
	},
];
